'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import React, { useEffect, useState } from 'react';
// import { Web3ReactProvider } from '@web3-react/core';
// import { Web3Provider as EthersWeb3Provider } from '@ethersproject/providers';
// import Web3Provider from "../../components/Web3Provider";
// import RainbowKitProviderComponent from "../../components/RainbowKitProvider";
// import { ConnectButton } from '@rainbow-me/rainbowkit';
import WalletConnect from "./components/WalletConnect";

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const [provider, setProvider] = useState(null);

  const handleConnect = (provider) => {
    setProvider(provider);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex p-4">
          <WalletConnect onConnect={handleConnect}/>
        </div>
        {React.cloneElement(children, { provider })}
      </body>
    </html>
  );
}

